const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function harness(){
 const handlers={},stores=new Map();let claimed=false,skipped=false;const root='https://example.com/plato/';
 const caches={keys:async()=>[...stores.keys()],delete:async k=>stores.delete(k),open:async k=>{if(!stores.has(k))stores.set(k,new Map());const s=stores.get(k);return {addAll:async reqs=>{for(const r of reqs)s.set(r.url,new Response('asset'))},keys:async()=>[...s.keys()].map(url=>({url})),match:async r=>s.get(typeof r==='string'?r:r.url),put:async(r,v)=>s.set(typeof r==='string'?r:r.url,v)}}};
 const context={URL,Request,Response,caches,fetch:async()=>new Response('<meta content="v35-root-20260911-11-numeric-only">'),self:{location:{href:root+'sw.js'},addEventListener:(n,fn)=>handlers[n]=fn,skipWaiting:async()=>{skipped=true},clients:{claim:async()=>{claimed=true}}}};
 vm.runInNewContext(fs.readFileSync('sw.js','utf8'),context);
 return {root,stores,caches,context,get claimed(){return claimed},get skipped(){return skipped},life:async n=>{let p;handlers[n]({waitUntil:v=>p=v});await p},request:async(path,mode='navigate')=>{let p;handlers.fetch({request:{url:new URL(path,root).href,method:'GET',mode},respondWith:v=>p=v});return p}};
}
test('worker preloads deterministic release before activation and only removes scoped old caches',async()=>{const h=harness();await h.life('install');assert.equal(h.skipped,true);assert.equal([...h.stores.values()][0].size,8);await (await h.caches.open('oracle-plato-old')).put(h.root+'index.html',new Response('old'));await (await h.caches.open('oracle-plato-other')).put('https://example.com/other/index.html',new Response('other'));await h.life('activate');assert.equal(h.claimed,true);assert.equal(h.stores.has('oracle-plato-old'),false);assert.equal(h.stores.has('oracle-plato-other'),true)});
test('navigation caches matching build, preserves it across failed or newer responses, and works offline',async()=>{const h=harness();await h.life('install');assert.match(await (await h.request('./')).text(),/v35-root/);h.context.fetch=async()=>new Response('newer release');assert.equal(await (await h.request('./')).text(),'newer release');h.context.fetch=async()=>new Response('missing',{status:404});assert.match(await (await h.request('./')).clone().text(),/v35-root/);h.context.fetch=async()=>{throw Error('offline')};assert.match(await (await h.request('./')).clone().text(),/v35-root/)});
test('legacy URL redirects to root and unrelated pages bypass interception',async()=>{const h=harness();const r=await h.request('v35/');assert.equal(r.status,302);assert.equal(r.headers.get('location'),h.root);assert.equal(await h.request('../another/'),undefined);assert.equal(await h.request('audit/example.html'),undefined)});
