(function(){
'use strict';
const VERSION='3.5-phone-distilled-1';
const STORE='ORACLE_PLATO_V35_PHONE_V1';
const MAP={pb:'powerball',sat:'saturday',oz:'oz',sfl:'set_for_life',ww:'windfall'};
const W={
 powerball:{m2_06_sum_band:.1587839135,m2_08_spacing_pattern:.1587839135,m2_05_parity_structure:.1270271308,m1_18_temporal_month:.1241394632,m1_14_sum_conditional:.1239009799,m1_06_recency:.1164415366,m1_13_parity_conditional:.0996939665,m2_14_regime_structure:.0912290958},
 saturday:{m1_08_gap_zscore:.2414698068,m1_07_gap_pressure:.2224693524,m2_10_recurrence_structure:.1800802680,m2_05_parity_structure:.1350602010,m1_13_parity_conditional:.0736830346,m1_12_range_density:.0506135748,m2_04_range_structure:.0506135748,m1_11_position_density:.0460101876},
 oz:{m1_12_range_density:.1633024018,m2_04_range_structure:.1633024018,m2_06_sum_band:.1621858339,m1_14_sum_conditional:.1413402732,m2_13_feature_interactions:.1117271255,m1_10_pair_transition:.0888840731,m1_02_short_frequency:.0846289453,m2_11_signature_similarity:.0846289453},
 set_for_life:{m2_01_structural_draw_templates:.2225580422,m2_12_normalized_number_density:.2225580422,m2_10_recurrence_structure:.1937564132,m2_05_parity_structure:.1073515262,m1_05_exponential_frequency:.0904092089,m2_07_adjacency_structure:.0785498972,m2_09_position_transition:.0497482682,m1_13_parity_conditional:.0350686019},
 windfall:{m1_05_exponential_frequency:.1841527353,m1_03_medium_frequency:.1311399261,m1_02_short_frequency:.1252955115,m1_17_transition:.1152018064,m1_01_global_frequency:.1110525052,m1_04_long_frequency:.1110525052,m1_09_pair_association:.1110525052,m2_02_pair_graph:.1110525052}
};
const clamp=x=>Math.max(0,Math.min(1,x));
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))};
function normObj(o,n){const vals=[];for(let i=1;i<=n;i++)vals.push(o[i]||0);const lo=Math.min(...vals),hi=Math.max(...vals),d=hi-lo||1,r={};for(let i=1;i<=n;i++)r[i]=clamp(((o[i]||0)-lo)/d);return r}
function countNums(rows,n,decay){const o={};for(let i=1;i<=n;i++)o[i]=0;const L=rows.length;rows.forEach((r,idx)=>{const w=decay?Math.pow(.5,(L-1-idx)/decay):1;r[2].forEach(x=>{if(x<=n)o[x]+=w})});return normObj(o,n)}
function gaps(rows,n){const occ=Array.from({length:n+1},()=>[]);rows.forEach((r,i)=>r[2].forEach(x=>{if(x<=n)occ[x].push(i)}));const pressure={},z={};for(let x=1;x<=n;x++){const a=occ[x],cur=a.length?rows.length-1-a[a.length-1]:rows.length,gs=[];for(let j=1;j<a.length;j++)gs.push(a[j]-a[j-1]);const m=mean(gs)||rows.length/Math.max(1,a.length),s=sd(gs)||Math.max(1,m/2);pressure[x]=cur/(m+1e-9);z[x]=(cur-m)/s}return {pressure:normObj(pressure,n),z:normObj(z,n)}}
function pairMatrix(rows,n){const p=Array.from({length:n+1},()=>new Float64Array(n+1));rows.forEach((r,idx)=>{const w=Math.pow(.5,(rows.length-1-idx)/120),a=r[2].filter(x=>x<=n);for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){p[a[i]][a[j]]+=w;p[a[j]][a[i]]+=w}});return p}
function parityScore(rows,n){const oddCounts=rows.map(r=>r[2].filter(x=>x%2).length),target=Math.round(mean(oddCounts)),r=rows[0]?.[2].length||6,oddPref=target/r,o={};for(let x=1;x<=n;x++)o[x]=x%2?oddPref:1-oddPref;return normObj(o,n)}
function rangeScore(rows,n){const bins=5,cnt=Array(bins).fill(0);rows.slice(-120).forEach(r=>r[2].forEach(x=>cnt[Math.min(bins-1,Math.floor((x-1)*bins/n))]++));const m=Math.max(...cnt,1),o={};for(let x=1;x<=n;x++)o[x]=cnt[Math.min(bins-1,Math.floor((x-1)*bins/n))]/m;return o}
function positionScore(rows,n){const o={};for(let x=1;x<=n;x++)o[x]=0;rows.slice(-180).forEach(r=>{const a=r[2].filter(x=>x<=n).slice().sort((a,b)=>a-b);a.forEach((x,j)=>{const expected=(j+.5)*n/a.length;o[x]+=1/(1+Math.abs(x-expected))})});return normObj(o,n)}
function adjacencyScore(rows,n){const o={};for(let x=1;x<=n;x++)o[x]=0;rows.slice(-180).forEach((r,idx)=>{const w=Math.pow(.5,(rows.length-1-idx)/100),a=r[2].filter(x=>x<=n).slice().sort((a,b)=>a-b);for(let i=1;i<a.length;i++)if(a[i]-a[i-1]<=2){o[a[i]]+=w;o[a[i-1]]+=w}});return normObj(o,n)}
function sumBand(rows,n){const recent=rows.slice(-180),sums=recent.map(r=>r[2].reduce((a,b)=>a+b,0)),m=mean(sums),s=sd(sums)||1,o={};for(let x=1;x<=n;x++)o[x]=0;recent.forEach(r=>{const z=Math.abs(r[2].reduce((a,b)=>a+b,0)-m)/s,w=Math.exp(-z*z/2);r[2].forEach(x=>{if(x<=n)o[x]+=w})});return normObj(o,n)}
function monthScore(rows,n){const last=rows[rows.length-1],month=last?new Date(last[1]).getMonth():new Date().getMonth(),o={};for(let x=1;x<=n;x++)o[x]=0;rows.forEach(r=>{if(new Date(r[1]).getMonth()===month)r[2].forEach(x=>{if(x<=n)o[x]++})});return normObj(o,n)}
function pairScores(rows,n){const p=pairMatrix(rows,n),latest=rows[rows.length-1]?.[2].filter(x=>x<=n)||[],assoc={},graph={},trans={};for(let x=1;x<=n;x++){graph[x]=0;assoc[x]=0;trans[x]=0;for(let y=1;y<=n;y++)graph[x]+=p[x][y];latest.forEach(y=>assoc[x]+=p[x][y])}for(let i=1;i<rows.length;i++){const prev=rows[i-1][2].filter(x=>x<=n),cur=new Set(rows[i][2].filter(x=>x<=n));for(let x=1;x<=n;x++)if(cur.has(x))latest.forEach(y=>{if(prev.includes(y))trans[x]++})}return {assoc:normObj(assoc,n),graph:normObj(graph,n),trans:normObj(trans,n)}}
function recurrence(rows,n){const o={},tot={},den={};for(let x=1;x<=n;x++)o[x]=0,tot[x]=0,den[x]=0;for(let i=1;i<rows.length;i++){const a=new Set(rows[i-1][2]),b=new Set(rows[i][2]);for(let x=1;x<=n;x++)if(a.has(x)){den[x]++;if(b.has(x))tot[x]++}}for(let x=1;x<=n;x++)o[x]=den[x]?tot[x]/den[x]:0;return normObj(o,n)}
function signature(rows,n){const last=rows[rows.length-1],sig=r=>{const a=r[2].filter(x=>x<=n),sum=a.reduce((s,x)=>s+x,0),odd=a.filter(x=>x%2).length,lo=a.filter(x=>x<=n/3).length;return [Math.round(sum/(n*.25)),odd,lo]},target=sig(last),o={};for(let x=1;x<=n;x++)o[x]=0;rows.slice(0,-1).forEach(r=>{const q=sig(r),dist=Math.abs(q[0]-target[0])+Math.abs(q[1]-target[1])+Math.abs(q[2]-target[2]),w=1/(1+dist);r[2].forEach(x=>{if(x<=n)o[x]+=w})});return normObj(o,n)}
function featureSet(rows,n){const short=countNums(rows.slice(-40),n),medium=countNums(rows.slice(-120),n),long=countNums(rows.slice(-300),n),global=countNums(rows,n),expo=countNums(rows,n,80),g=gaps(rows,n),pair=pairScores(rows,n),par=parityScore(rows,n),range=rangeScore(rows,n),pos=positionScore(rows,n),adj=adjacencyScore(rows,n),sum=sumBand(rows,n),month=monthScore(rows,n),rec=recurrence(rows,n),sig=signature(rows,n),recent=countNums(rows.slice(-40),n),older=countNums(rows.slice(-200,-40),n),reg={};for(let x=1;x<=n;x++)reg[x]=clamp(.65*recent[x]+.35*older[x]-.25*Math.abs(recent[x]-older[x]));return {short,medium,long,global,expo,g,pair,par,range,pos,adj,sum,month,rec,sig,reg:normObj(reg,n)}}
function methodScore(id,x,f,rows){switch(id){case'm1_01_global_frequency':return f.global[x];case'm1_02_short_frequency':return f.short[x];case'm1_03_medium_frequency':return f.medium[x];case'm1_04_long_frequency':return f.long[x];case'm1_05_exponential_frequency':return f.expo[x];case'm1_06_recency':{let since=rows.length;for(let i=rows.length-1;i>=0;i--)if(rows[i][2].includes(x)){since=rows.length-1-i;break}return Math.exp(-since/12)}case'm1_07_gap_pressure':return f.g.pressure[x];case'm1_08_gap_zscore':return f.g.z[x];case'm1_09_pair_association':return f.pair.assoc[x];case'm1_10_pair_transition':return f.pair.trans[x];case'm1_11_position_density':return f.pos[x];case'm1_12_range_density':return f.range[x];case'm1_13_parity_conditional':return f.par[x];case'm1_14_sum_conditional':return f.sum[x];case'm1_17_transition':return clamp(.55*f.pair.trans[x]+.45*f.rec[x]);case'm1_18_temporal_month':return f.month[x];case'm2_01_structural_draw_templates':return clamp(.45*f.sig[x]+.3*f.sum[x]+.25*f.par[x]);case'm2_02_pair_graph':return f.pair.graph[x];case'm2_04_range_structure':return f.range[x];case'm2_05_parity_structure':return f.par[x];case'm2_06_sum_band':return f.sum[x];case'm2_07_adjacency_structure':return f.adj[x];case'm2_08_spacing_pattern':return clamp(.6*f.adj[x]+.4*f.pos[x]);case'm2_09_position_transition':return clamp(.55*f.pos[x]+.45*f.pair.trans[x]);case'm2_10_recurrence_structure':return f.rec[x];case'm2_11_signature_similarity':return f.sig[x];case'm2_12_normalized_number_density':return clamp(.5*f.global[x]+.5*f.range[x]);case'm2_13_feature_interactions':return Math.sqrt(Math.max(0,f.short[x]*f.g.pressure[x]*f.pair.trans[x]));case'm2_14_regime_structure':return f.reg[x];default:return 0}}
function rank(game){const cfg=GAME_CFG[game],rows=currentRows(game).slice().sort((a,b)=>a[0]-b[0]),key=MAP[game],weights=W[key];if(!cfg||!weights)throw new Error('Unsupported game');if(rows.length<60)throw new Error('Not enough history');const f=featureSet(rows,cfg.n),out=[];for(let x=1;x<=cfg.n;x++){let s=0;for(const [id,w] of Object.entries(weights))s+=w*methodScore(id,x,f,rows);out.push({number:x,score:s})}out.sort((a,b)=>b.score-a.score||a.number-b.number);return {rows,weights,out}}
function chooseK(game){try{if(window.PLATO_V34)return PLATO_V34.recommend(game).k}catch(_){ }return 15}
function run(){const game=document.getElementById('v35Game').value,k=+document.getElementById('v35K').value||chooseK(game),r=rank(game),top=r.out.slice(0,k),box=document.getElementById('v35Out');box.textContent=`PLATO v3.5 distilled phone\n${GAME_CFG[game].name}\nPool ${k}\n${top.map(x=>String(x.number).padStart(2,'0')).join(' ')}\n\n8 distilled methods: ${Object.entries(r.weights).map(([id,w])=>id+' '+(w*100).toFixed(1)+'%').join(' · ')}\n\nExperimental development model — not verified predictive edge.`;localStorage.setItem(STORE,JSON.stringify({version:VERSION,createdAt:new Date().toISOString(),game,k,pool:top.map(x=>x.number),scores:top}))}
function adaptive(){const g=document.getElementById('v35Game').value,k=chooseK(g);document.getElementById('v35K').value=k;document.getElementById('v35Out').textContent=`Adaptive pool selected: ${k}. Press Run v3.5.`}
function install(){if(document.getElementById('v35phone'))return;const nav=document.getElementById('nav'),main=document.querySelector('main');if(!nav||!main)return;const b=document.createElement('button');b.textContent='v3.5';b.onclick=()=>{document.querySelectorAll('main section').forEach(s=>s.classList.remove('shown'));document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('on'));document.getElementById('v35phone').classList.add('shown');b.classList.add('on')};nav.appendChild(b);const sec=document.createElement('section');sec.id='v35phone';sec.innerHTML=`<div class="card"><h2>PLATO v3.5 distilled phone</h2><p class="note">Heavy 35-method training stays off-device. This phone layer runs only the eight distilled methods selected for each game. Historical training results are development evidence, not confirmation.</p><div class="grid"><div><label>Game</label><select id="v35Game"></select></div><div><label>Pool size</label><input id="v35K" type="number" value="15" min="7" max="30"></div></div><button class="secondary" id="v35Adaptive">Use v3.4 adaptive pool size</button><button class="primary" id="v35Run">Run v3.5</button><pre id="v35Out">Ready.</pre></div>`;main.appendChild(sec);const sel=sec.querySelector('#v35Game');for(const [k,c] of Object.entries(GAME_CFG)){const o=document.createElement('option');o.value=k;o.textContent=c.name;sel.appendChild(o)}sel.value='pb';sec.querySelector('#v35Run').onclick=run;sec.querySelector('#v35Adaptive').onclick=adaptive}
window.PLATO_V35={VERSION,rank,run,chooseK};install();
})();
